### ISSUE TITLE
Kobo Miniclock Battery Display

### ISSUE THREAD

**Issue by bansheeat** [frostschutz/Kobo#10]
I managed to show Time and Battery in my Book, but after page turn only time shows and battery is no longer displayed.
Here is my Configuration, my Reader is Kobo Aura H2o 2nd Edition FW: 4.4.9298
[Batteryminiclock.txt](https://github.com/frostschutz/Kobo/files/10833461/Batteryminiclock.txt)

**Comment by frostschutz** [comment]
everything here is outdated and unmaintained, sorry

use nanoclock instead or the nickel clock patch, you can find either one on MR

**Comment by bansheeat** [comment]
Hi Andreas,

 

sorry to have bothered you, I already noticed the new program.

 

Regards

 

Von: Andreas Klauer ***@***.***> 
Gesendet: Sonntag, 26. Februar 2023 12:18
An: frostschutz/Kobo ***@***.***>
Cc: bansheeat ***@***.***>; Author ***@***.***>
Betreff: Re: [frostschutz/Kobo] Kobo Miniclock Battery Display (Issue #10)

 

everything here is outdated and unmaintained, sorry

use nanoclock instead or the nickel clock patch, you can find either one on MR
