### ISSUE TITLE
Screensaver not working on Kobo Glo HD

### ISSUE THREAD

**Issue by siqueira-ec** [frostschutz/Kobo#5]
I've tried to install and reinstall, still not working.

fbset.txt:

mode "1072x1448-45"
	# D: 80.000 MHz, H: 65.681 kHz, V: 45.049 Hz
	geometry 1072 1448 1088 3072 32
	timings 12500 16 102 4 4 28 2
	accel false
	rgba 8/16,8/8,8/0,8/24
endmode

**Comment by frostschutz** [comment]
There are two known problems with the screensaver mod (1) scanline doesn't handle the new RGBA pixel format properly, (2) the pngshow no longer updates the screen properly, now causes ghosting [something changed in the eink kernel driver]. I haven't found the time to tackle these yet.

Even so, while not perfect, it still works on my H2O regardless, even in 4.6.9960 firmware. Scanlines show up, get written to the screensaver.cfg, and then the screensaver images start showing up.

I don't know why it fails completely on the Glo HD and other devices. I can only test on my H2O and an old Glo with two thirds of its display broken.

**Comment by frostschutz** [comment]
ScreenSaver now uses fbink and scanline ignores RGBA alpha channel.

I don't know if that solves issues with all devices (there are some issues with Kobo Forma in landscape mode), but it should be a huge improvement in any case.
