### ISSUE TITLE
Installation with Mac

### ISSUE THREAD

**Issue by acrobat22** [frostschutz/Kobo#6]
Hello. Thank you for your excellent work and for sharing.

I am trying to install MiniClock on my kobo libra H20 (firmware V 4.19).
It doesn't work.

I unzip the file and with the terminal I create a .tgz -> tar -cvzf KoboRoot.tgz KoboRoot-MiniClock-20190729b
And i put this folder in eReader to .Kobo and eject this and disconnect the USB cable.

The eReader reboot but i don't find files in addons folder.

I don't understand why ?

Could you help me ?

Thank you so much

**Comment by frostschutz** [comment]
You're not supposed to create a tgz. The download link in the forum already is a tgz. If you're using a greedy unzipper (that also extracts the tgz inside the zip) find a way to disable that or use a different program (so you get the original, unmodified tgz). I don't have a Mac so I don't really know, in Windows you could do it with 7-zip and in Linux with the regular commandline unzip.

**Comment by frostschutz** [comment]
If you must create your own tgz anyway, you have to make sure of the correct directory structure and executable flags inside the tgz.
Finally, it's named KoboRoot-MiniClock-12345.tgz just so you know what it is; when you copy it to the kobo, it has to be named .kobo/KoboRoot.tgz
Even so it's best to just use the provided tgz as is

**Comment by pgaskin** [comment]
And if you still have issues creating a tarball or already use kobopatch, you can use the files section of kobopatch.yaml (all files are created with the executable bit set, and you have complete control over the stored filename).

**Comment by acrobat22** [comment]
> If you must create your own tgz anyway, you have to make sure of the correct directory structure and executable flags inside the tgz.
> Finally, it's named KoboRoot-MiniClock-12345.tgz just so you know what it is; when you copy it to the kobo, it has to be named .kobo/KoboRoot.tgz
> Even so it's best to just use the provided tgz as is

Thank you very much, I had configured my dezip incorrectly.
It's ok now.

**Comment by acrobat22** [comment]
> And if you still have issues creating a tarball or already use kobopatch, you can use the files section of kobopatch.yaml (all files are created with the executable bit set, and you have complete control over the stored filename).

I don't know this technique.
I will document myself. thank you very much for the information
